---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: Delete content & directory
    file:
       state: absent
       path: /tmp/docker_{{BUILD_NUMBER}}-1
  - name: create directory 
    file:
       path: /tmp/docker_{{BUILD_NUMBER}}
       state: directory
 
  - name: Get the dockerfile
    git: repo=https://github.com/vijayasanthi20/CD_CD_project.git dest=/tmp/docker_{{BUILD_NUMBER}}
  
  - name: build the docker file
    command: docker build -t viji20/docker_swarm_project:{{BUILD_NUMBER}} -f Dockerfile .
    args:
         chdir: /tmp/docker_{{BUILD_NUMBER}}
  - name: run the docker
    command: docker run -itd -P viji20/docker_swarm_project:{{BUILD_NUMBER}}
