---
- hosts: webservers
  become: true
  become_user: root
  tasks:
  - name: create directory 
    file:
       path: /tmp/docker_{{BUILD_NUMBER}}
       state: directory
  - name: Get the dockerfile
    git: repo=https://github.com/vijayasanthi20/CD_CD_project.git dest=/tmp/docker_{{BUILD_NUMBER}}
  - name: build the docker file
    command: chdir=/tmp/docker_{{BUILD_NUMBER}}/docker build -t viji20/docker_swarm_project:{{BUILD_NUMBER}} .
  - name: run the docker
    command: docker run -itd -P viji20/docker_swarm_project:{{BUILD_NUMBER}}
